name: Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Test with coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - run: npm ci

      - name: Test with coverage
        run: npm run test

      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
